### ISSUE TITLE
prov:hadRole usage

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#141]
@bduggan @zednis As described in the discussion accessible on the page available at:
https://github.com/USGCRP/gcis-ontology/issues/2

Searching on sindice, specifically:
http://sindice.com/search?q=role

The sixth item that comes up is a TW term "has role." Unfortunately, the linked to page is no longer available. Could we create or utilize a term which can be used with a literal value?  e.g.:
http://data.globalchange.gov/person/1025.thtml

**Comment by bduggan** [comment]
Instead of creating a new term, let's just make roles into first class objects.  I will add support for /role and /role/:role_identifier endpoints, and then those literals can be replaced with URIs.  The data model already supports this (i.e. there is a [role table](https://github.com/USGCRP/gcis/blob/master/db/dist/docs/pod/table_role_type.pod)).

**Comment by zednis** [comment]
:+1: to Brian's suggestion.

**Comment by bduggan** [comment]
There is now an endpoint for roles (4f1871fe016233b0d891745c657fb2da20e16a5f), and an HTML rendering for a role. (called "role_type" in the schema).
Also hadRole now uses URI's rather than literals: (ccc79b079c19866c2aeb1e651d954087a52a04f6)

**Comment by justgo129** [comment]
I like this very much.  Just a point of information that we have items in the GCIS Ontology for "Convening Lead Author," etc.  We'll need to broaden the definitions to incorporate non-NCA3 documents but I wouldn't call it a priority.

**Comment by bduggan** [comment]
This is done and in production.
Note there were a couple of little punctuation issues: 46fd47e915af0e427b4ff7a99d9024769ce9df62 ff1f2b58bd9d52694d7bc0bda9de8769687918f0
