### ISSUE TITLE
Link people with DBPedia

### ISSUE THREAD

**Issue by CurtTilmes** [USGCRP/gcis#212]
Interesting.

There probably aren't many of these, but
    http://data.globalchange.gov/person/1466
is the same as
    http://dbpedia.org/page/Thomas_R._Karl

DBpedia also nicely links to several other databases (WorldCat, VIAF, LCCN)

GCIS claims foaf:givenName "Tom" whereas dbpedia has foaf:givenName "Thomas R."

Should GCIS establish those links where we find them?

**Comment by bduggan** [comment]
Yes, there are a few other "notable people" in gcis, and we should add their dbpedia identifiers (using the dbpedia lexicon).  I'm closing this since no changes to the software are necessary, and we'll include this in some more general management of the gcis records for people, currently iin progress.
