### ISSUE TITLE
question on current model_run template

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis#236]
https://github.com/USGCRP/gcis/blob/master/lib/Tuba/files/templates/model_run/object.ttl.tut

Does this template correspond to a ``gcis:ModelRun`` or a ``gcis:ModelRunOuput`` as discussed in https://github.com/USGCRP/gcis-ontology/issues/17?

@bduggan Looking at the template I think this looks like instance data for an instance of ``gcis:ModelRunOutput``, but I am not sure.

**Comment by bduggan** [comment]
Despite the conversation in usgcrp/gcis-ontology#17, "model run" is often used to refer to the output.  Examples: http://cmip-pcmdi.llnl.gov/cmip5/getting_started_CMIP5_experiment.html 
I am think defining "model run" in a way that conflicts with the common usage (i.e. defining it as an activity rather than a dataset) will be confusing.

**Comment by bduggan** [comment]
This has been resolved, it is ModelRunOutput.
