### ISSUE TITLE
Allow PubMed IDs for articles (as alternative to DOIs) 

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#315]
Corollary for #314.  For applicable NCA3 articles without dois but which have PubMed IDs, incorporate PubMed IDs into GCIS

**Comment by justgo129** [comment]
The identifiers for these articles have been adjusted accordingly, i.e., they all have identifiers beginning with "pmc" or "pmid."  As PubMed provides both, we need to first check that PMC identifiers are not confused with PMID ones within the GCIS identifier system.  We then need to store those identifier values within GCIS and update the identifier scheme accordingly.

**Comment by lomky** [comment]
@justgo129 @amruelama I am okay if we want to create a convention going forward for articles where we will set their identifier to doi (if exists), otherwise pubmed, (if exists), and falling back to a gcis generated identifier.

I do not see any value in re-doing the identifiers of the existing articles. These are internal IDs. 

We should definitely link to any existing PubMed URLs that exist.

**Comment by lomky** [comment]
@justgo129 You can already create the identifier as the PMID when creating an article.

**Comment by lomky** [comment]
Discussion with @justgo129 

We are mostly concerned storing the PubMed ID somewhere, similar to how we can store the DOI separately from the identifier. Maybe through a separate table (1-to-many) supporting various other identifiers or by on-demand query to the PubMed ID.
