### ISSUE TITLE
Incorporate BCO-DMO (WHOI) oceanographic content and foster vocabulary from Natural Environment Research Council (NERC)

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#339]
Incorporate BCO-DMO (WHOI) oceanographic **content** and foster **vocabulary** from Natural Environment Research Council (NERC).

**Comment by lomky** [comment]
@justgo129 is this a standard thing we have a process for, and if so can you point to a previous incorporation?

**Comment by justgo129** [comment]
Nope, it was just something we've been talking about doing for a while.

**Comment by rewolfe** [comment]
Kat, We've used various scripts in to add these vocabularies.  This script
added the GovMan vocabulary:
https://github.com/USGCRP/gcis-scripts/blob/master/govman-agency.pl

Note, we try to only add terms when GCIS URIs already exist.  There is no
current process for adding additional terms when new GCIS URIs are added.
For instance, there may have been a new gov org added during the health
assessment that has an acronym in GovMan, but it has not been added yet.
There is a long-term maintainance issue with these vocabularies since
usually a manual match is needed and the external lists and GCIS URIs
evolve over time.

On Tue, Jun 21, 2016 at 10:13 AM, justgo129 <notifications@github.com>
wrote:

> Nope, it was just something we've been talking about doing for a while.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/339#issuecomment-227452720>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHR7GWTA9FYCYyTMbgXTCYT0Dbz3zIMBks5qN_GhgaJpZM4INIIQ>
> .
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966
