### ISSUE TITLE
Adding two or more URLs in one field

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#354]
[This dataset](https://data-stage.globalchange.gov/dataset/esa-cci-soil-moisture-microwave-sm-mw) has two URLs related to it -
1. A [paper with methodology](http://www.sciencedirect.com/science/article/pii/S0034425712001332)  and
2. A [Webpage where the dataset can be downloaded](http://www.esa-soilmoisture-cci.org/node/145). But I couldn't add both in the same field with HTML tags. 
It would be great to have two or more URLs in same field, separated by comma or a link break

Note: For now, I have added the dataset's page to URL field and the paper's DOI to DOI field.

**Comment by lomky** [comment]
I suggest creating the article describing the dataset (1) as an article and using a Relationship to connect it to the dataset.

(2) should go into the URL for the dataset.

**Comment by amruelama** [comment]
Used '**prov:wasInformedBy**' to relate this dataset to the article. Please note that in this case, although the article describes the methodology of the derived product (**combined product**), it doesn't cite or name the dataset. So, in GCIS database, we have created a name '_Soil Moisture Microwave_' for the combined product and related it to the article as well as the the figure derived from this dataset. This is may be temporary. 
@rasherman Any thoughts?

**Comment by lomky** [comment]
@justgo129 is there a more accurate relationship that you know?

**Comment by justgo129** [comment]
Sure, @amruelama it may be worthwhile to check out:

- datacite:hasdescription (http://purl.org/spar/datacite/hasDescription) 
This should work since datacite:hasDescription has the range of datacite:hasDescriptionType.  One option for datacite:hasDescriptionType is "other."   For the other way, we could use the generic dcterms:description which is used elsewhere in GCIS.  I'd believe an article could fall into the range of that property.  See: http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#description

- cito:describes or cito:isDescribedby http://purl.org/spar/cito/describes http://purl.org/spar/cito/isDescribedBy

Note that it's all right that the cito ones mentioned above are subclasses of cito:cites and cito:isCitedBy since they permit indirect citations

**Comment by amruelama** [comment]
Add new field **Download URL**
