### ISSUE TITLE
Create a Report Citation Summary tool for a report

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#486]
Following the work done with the #485 and the evaluation section 2:

Given a report that has just completed, run this script to create a report with all the datasets, references, etc used to create the report that can be distributed to agency PoCs for distribution & acknowledgements. 

@rasherman please feel free to add clarification.

**Comment by rasherman** [comment]
Going through old tickets just to see if there are things I've forgotten about and should bring back up. Responding to this since I was mentioned:

I don't think there's much more to say. This can be fairly simple and no-frills, I can just envision something that runs through the report and spits out something for each agency like:

EPA provided key support to the NCA including:
XX Authors of the NCA
XX Publications cited in the NCA with EPA-affiliated authors
XX Datasets from which figures/tables were derived
