### ISSUE TITLE
Populate articles metadata

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#543]
- [x] Query articles with no DOI or URL 
- [x] Find DOI (first priority) or URL for the articles and populate them
- [x] Make sure this query returns 0 rows 
` SELECT * FROM article where DOI is NULL  AND URL is NULL;`

**Comment by amruelama** [comment]
List of articles with no DOI and URL and status update [spreadsheet](https://docs.google.com/a/usgcrp.gov/spreadsheets/d/1q3AAH2_AlrSV5cz7X3G-APuR2tuWO-kMxKMyUDCeajg/edit?usp=sharing)

**Comment by amruelama** [comment]
@rasherman. Could you review the three articles from above spreadsheet please? The updates will go to production this Wednesday.

**Comment by rasherman** [comment]
Reviewed. Looks like these journals have some poorly kept online archives. I can't find any better info that what you have already got, and can't find any record of the "submitted" one to confirm whether or not it was published in the end, since the journal doesn't even have tables of contacts of their archives online.

**Comment by amruelama** [comment]
Thank you! Closing this issue since all the articles (except "Climate downscaling..") have either DOI or URL.
