### ISSUE TITLE
Formatting problems regarding Author page on data-stage

### ISSUE THREAD

**Issue by R-Aniekwu** [USGCRP/gcis#638]
Contributor field mismatch - the name of the author's affiliation is listed under the "role" field, and the author's role is listed under the "publication" field.

https://data-stage.globalchange.gov/person/10237.

**Comment by lomky** [comment]
This is because the person has an incorrect `Contributor` connection with an `Organization` but no `Publication`. That is not a correct connection in our system. (A person is only affiliated with Organizations in our system _though_ publishing, not inherently). 

Is that understanding correct, @amruelama? If so, the solution is to delete the bad `Contributor` relation.

![screenshot-2018-5-15 - gcis](https://user-images.githubusercontent.com/6129479/40066232-ad909fe0-5831-11e8-92d9-1e2c12556b55.png)
